#!/bin/bash

BOLD="\e[1;97m"
GREEN="\e[32m"
CYAN="\e[36m"
ENDCOLOR="\e[0m"

VERSION=$1
if [ -z "${VERSION}" ]; then
   echo -e "Syntax: publish_unistring <version>\nExample: publish_unistring 1.0\n";
   exit 0
fi

echo -e "${GREEN}Downloading libunistring ${VERSION} ${ENDCOLOR}";
WGET="wget https://ftp.gnu.org/gnu/libunistring/libunistring-${VERSION}.tar.gz";
echo ${WGET}
command ${WGET} 2>/dev/null;

echo -e "\n${GREEN}Writing libunistring.${VERSION}.yaml${ENDCOLOR}";
cp ./libunistring.ingredient.yaml libunistring.${VERSION}.yaml;
sed -i "s/VERSION/${VERSION}/g" libunistring.${VERSION}.yaml;
echo libunistring.${VERSION}.yaml;

echo -e "\n${GREEN}This metadata was manually created for libunistring: ${CYAN}\n"
cat libunistring.${VERSION}.yaml;
echo -e "\n${GREEN}If that looks good, run state publish using the command below:${ENDCOLOR}\n"

COMMAND="state publish --meta libunistring.${VERSION}.yaml libunistring-$VERSION.tar.gz"
echo -e "${BOLD} # $COMMAND ${ENDCOLOR}\n\n";
