#!/bin/bash

VERSION=$1
if [ -z "${VERSION}" ]; then
   echo -e "Syntax: publish_unistring <version>\nExample: publish_unistring 1.0\n";
   exit 0
fi

echo "Downloading libunistring ${VERSION}\n";
wget https://ftp.gnu.org/gnu/libunistring/libunistring-${VERSION}.tar.gz;

echo "Writing libunistring.${VERSION}.yaml";
cp ./libunistring.ingredient.yaml libunistring.${VERSION}.yaml;
sed -i "s/VERSION/${VERSION}/g" libunistring.${VERSION}.yaml;

COMMAND="state publish --meta libunistring.${VERSION}.yaml libunistring-$VERSION.tar.gz"
echo $COMMAND;
command $COMMAND;

